name: Profile Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-profile-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Monophonique91 Profile Metrics (left)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 3
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_notable: yes
          plugin_notable_repositories: yes
          config_order: base.header, isocalendar, languages, notable, topics

      - name: Monophonique91 Profile Metrics (right)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.personal.anilist.svg
          token: ${{ secrets.METRICS }}
          plugin_anilist: yes
          plugin_anilist_medias: techno
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          config_order: anilist